config/routes.rb
Rails.application.routes.draw do
  resources :cocktails, only: [:show, :index, :new, :create] do
    resources :doses, only: [:create]
  end

  resources :doses, only: [:destroy]

  resources :ingredients, only: [:show]

  root "cocktails#index"

  mount Attachinary::Engine => "/attachinary"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
    validates :name, presence: true, uniqueness: true

    has_many :doses, dependent: :destroy
    has_many :ingredients, through: :doses
    # mount_uploader :photo, PhotoUploader
    has_attachment :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
    belongs_to :cocktail
    belongs_to :ingredient
    # validates :ingredient, uniqueness: true
    validates :description, presence: true

    validates :cocktail, presence: true
    validates :ingredient, presence: true
    validates :ingredient, uniqueness: { scope: :cocktail }

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    validates :name, presence: true, uniqueness: true

    has_many :doses
    has_many :cocktails, through: :doses

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
      @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
    @ingredients = Ingredient.all
  end

  def new
      @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)

  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      @ingredients = Ingredient.all
      render 'cocktails/show'
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def show
    @ingredient = Ingredient.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
    <%= f.input :name, placeholder: "Mojito" %>
    <%= f.input :photo, as: :attachinary %>
    <%= f.button :submit, class: "btn btn-primary"  %>
<% end %>

app/views/cocktails/index.html.erb
    <%= render 'layouts/shared/banner' %>

<h1 class="text-center">Your cocktail list</h1>



<div class="container">
  <div class="row">
    <% @cocktails.each do |cocktail| %>
      <div class="col-xs-12 col-sm-4">
      <%= link_to cocktail_path(cocktail) do %>
        <div class="card" style="background-image: url('<%= cl_image_path cocktail.photo.path%>');">
          <div class="card-description">
            <h2><%= cocktail.name %></h2>
          </div>
        </div>
      <% end %>
     </div>



    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>New Cocktail</h1>
      <%= render 'form' %>
      <%= link_to 'Back', cocktails_path %>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1><%= @cocktail.name %></h1>
      <%= cl_image_tag @cocktail.photo.path, width: 300, height: 200, crop: :fill %>

      <ul class="list-unstyled">
        <% @cocktail.doses.each do |dose| %>
          <li><%= link_to dose.ingredient.name, ingredient_path(dose.ingredient) %> : <%= dose.description %> <%= link_to "<i class='fa fa-close'></i>".html_safe, dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } %></li>
        <% end %>
      </ul>
      <br>
      <% if @dose.errors.any? %>
        <ul>
          <% @dose.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      <%= simple_form_for([@cocktail, @dose]) do |f| %>
        <%= f.input :description %>
        <%= f.input :ingredient_id, collection: @ingredients %>
        <%= f.submit class: "btn btn-primary" %> <%= link_to 'Back', cocktails_path, class: "btn btn-primary" %>
      <% end %>

    </div>
  </div>
</div>

app/views/ingredients/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1><%= @cocktail.name %></h1>
      <ul class="list-unstyled">
        <% @cocktail.doses.each do |dose| %>
          <li><%= link_to dose.ingredient.name, ingredient_path(dose.ingredient) %> : <%= dose.description %> <%= link_to "<i class='fa fa-close'></i>".html_safe, dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } %></li>
        <% end %>
      </ul>
      <br>
      <% if @dose.errors.any? %>
        <ul>
          <% @dose.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      <%= simple_form_for([@cocktail, @dose]) do |f| %>
        <%= f.input :description %>
        <%= f.input :ingredient_id, collection: @ingredients %>
        <%= f.submit class: "btn btn-primary" %>
      <% end %>
      <%= link_to 'Back', cocktails_path %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>


    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= cloudinary_js_config %>
  </head>

  <body>

    <%= render 'layouts/shared/navbar' %>

    <%= yield %>

    <%= render 'layouts/shared/footer' %>

  </body>
</html>

app/views/layouts/shared/_banner.html.erb
<div class="banner" style="background-image: url('http://419a5ecf000c70751b96-2d268c5dae618615daa5314a1f0f4b99.r77.cf1.rackcdn.com/restaurants-irs/235125/EclipseCocktails1.png');"">
  <div class="banner-content">
    <h1>Welcome to the Mecca of Cocktails</h1>
    <p>The home of sharing the coolest cocktails</p>
    <%= link_to "Create a cocktail", new_cocktail_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/layouts/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
</div>

app/views/layouts/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <h5><i class="fa fa-glass" aria-hidden="true"></i>COCKweiBA</h5>
    <!-- <%= image_tag "logo.png" %> -->
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Links -->
    <%= link_to "Create A Drink", new_cocktail_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <!-- Avatar with dropdown menu -->
 <!--    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div> -->
  </div>


  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Hello link 1</a></li>
        <li><a href="#">Hello link 2</a></li>
        <li><a href="#">Hello link 3</a></li>
      </ul>
    </div>
  </div>
</div>